server:
  port: 8091

spring:
  application:
    name: user-ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authgw?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 271631126
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
